name = "JAM"
uuid = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
version = "7.1.0"
authors = ["hq@rotko.net"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BatchedMerkleTree = "225b011c-e439-4471-b39b-04a9a0fe32f0"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BinaryFields = "0fee9d7f-8397-4f0d-9ec6-117db1666467"
BinaryReedSolomon = "8a283c49-c6d0-46c5-bbc1-5b2a51f34960"
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Keccak = "46f8cb0c-4e3a-418e-8a08-140a605d534d"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Quic = "e87bf339-ccdf-4a5f-9274-4a3c1e6e3c8f"
SDL2_jll = "ab825dc5-c88e-5901-9575-1e5e20358fcf"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SimpleDirectMediaLayer = "98e33af6-2ee5-5afd-9e75-cbc738b767c4"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UnsafeArrays = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"

[sources]
Quic = {rev = "v0.4.0", url = "https://github.com/rotkonetworks/quic.jl"}

[compat]
BenchmarkTools = "1.6.3"
Comonicon = "1.0.8"
PackageCompiler = "2.2.3"
PrecompileTools = "1.3.3"
SDL2_jll = "2.32.10"
SimpleDirectMediaLayer = "0.5.0"
StructArrays = "0.7.2"
UnsafeArrays = "1.0.8"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
