[package]
name = "bandersnatch-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
ark-vrf = { git = "https://github.com/davxy/ark-vrf", features = ["bandersnatch", "ring"] }
ark-serialize = "0.5"

[profile.release]
lto = true
opt-level = 3
