[package]
name = "enomt-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nomt = { path = "/home/alice/rotko/enomt/nomt", default-features = false }
blake2 = "0.10"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
